# Generated by Django 6.0.4 on 2026-04-24 14:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('egresado', 'Egresado'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado')),
                ('usuario', models.OneToOneField(limit_choices_to={'perfil__rol': 'estudiante'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['usuario__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_general', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Promedio General')),
                ('creditos_cursados', models.IntegerField(default=0, verbose_name='Créditos Cursados')),
                ('creditos_aprobados', models.IntegerField(default=0, verbose_name='Créditos Aprobados')),
                ('asignaturas_completadas', models.IntegerField(default=0, verbose_name='Asignaturas Completadas')),
                ('asignaturas_aprobadas', models.IntegerField(default=0, verbose_name='Asignaturas Aprobadas')),
                ('estado_general', models.CharField(choices=[('activo', 'Activo'), ('completado', 'Completado'), ('en_prueba', 'En Prueba Académica'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado General')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expediente', to='academico.estudiante', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['estudiante'],
            },
        ),
        migrations.CreateModel(
            name='ActaCulminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('fecha_graduacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Graduación')),
                ('numero_acta', models.CharField(max_length=100, unique=True, verbose_name='Número de Acta')),
                ('promedio_final', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Promedio Final')),
                ('titulo_otorgado', models.CharField(max_length=200, verbose_name='Título Otorgado')),
                ('estado', models.CharField(choices=[('generada', 'Generada'), ('registrada', 'Registrada'), ('entregada', 'Entregada')], default='generada', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acta_culminacion', to='academico.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Acta de Culminación',
                'verbose_name_plural': 'Actas de Culminación',
                'ordering': ['fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Maestría')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('creditos_totales', models.IntegerField(default=0, verbose_name='Créditos Totales')),
                ('duracion_semestres', models.IntegerField(default=4, verbose_name='Duración en Semestres')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('coordinador', models.ForeignKey(limit_choices_to={'perfil__rol': 'coordinador'}, on_delete=django.db.models.deletion.PROTECT, related_name='maestrias_coordinadas', to=settings.AUTH_USER_MODEL, verbose_name='Coordinador')),
            ],
            options={
                'verbose_name': 'Maestría',
                'verbose_name_plural': 'Maestrías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='maestria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='academico.maestria', verbose_name='Maestría'),
        ),
        migrations.CreateModel(
            name='ModuloMaestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_modulo', models.IntegerField(verbose_name='Número de Módulo')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Módulo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('semestre', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Semestre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('maestria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='academico.maestria', verbose_name='Maestría')),
            ],
            options={
                'verbose_name': 'Módulo de Maestría',
                'verbose_name_plural': 'Módulos de Maestría',
                'ordering': ['maestria', 'semestre'],
                'unique_together': {('maestria', 'numero_modulo')},
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Asignatura')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código de Asignatura')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('creditos', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Créditos')),
                ('horas_teoricas', models.IntegerField(default=0, verbose_name='Horas Teóricas')),
                ('horas_practicas', models.IntegerField(default=0, verbose_name='Horas Prácticas')),
                ('es_obligatoria', models.BooleanField(default=True, verbose_name='Es Obligatoria')),
                ('calificacion_minima', models.DecimalField(decimal_places=1, default=3.0, max_digits=3, verbose_name='Calificación Mínima')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='academico.modulomaestria', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['modulo', 'nombre'],
                'unique_together': {('modulo', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ProfesorAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesores', to='academico.asignatura', verbose_name='Asignatura')),
                ('profesor', models.ForeignKey(limit_choices_to={'perfil__rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_profesor', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Profesor-Asignatura',
                'verbose_name_plural': 'Profesor-Asignatura',
                'ordering': ['asignatura', 'profesor'],
                'unique_together': {('profesor', 'asignatura')},
            },
        ),
        migrations.CreateModel(
            name='InscripcionModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('estado_inscripcion', models.CharField(choices=[('inscrito', 'Inscrito'), ('cursando', 'Cursando'), ('completado', 'Completado'), ('retirado', 'Retirado')], default='inscrito', max_length=20, verbose_name='Estado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_modulo', to='academico.estudiante', verbose_name='Estudiante')),
                ('maestria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_estudiantes', to='academico.maestria', verbose_name='Maestría')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='academico.modulomaestria', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Inscripción en Módulo',
                'verbose_name_plural': 'Inscripciones en Módulo',
                'ordering': ['maestria', 'estudiante'],
                'unique_together': {('estudiante', 'modulo')},
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_final', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota Final')),
                ('nota_parcial1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota Parcial 1')),
                ('nota_parcial2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota Parcial 2')),
                ('nota_trabajo', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota de Trabajo')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.asignatura', verbose_name='Asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='academico.estudiante', verbose_name='Estudiante')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='academico.profesorasignatura', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'ordering': ['estudiante', 'asignatura'],
                'unique_together': {('estudiante', 'asignatura')},
            },
        ),
    ]
