# Generated by Django 6.0.4 on 2026-04-24 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('coordinador', 'Coordinador de Maestría'), ('profesor', 'Profesor'), ('estudiante', 'Estudiante'), ('secretaria', 'Secretaria Docente')], default='coordinador', max_length=20, verbose_name='Rol del Usuario')),
                ('numero_identidad', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
                'ordering': ['usuario__first_name'],
            },
        ),
    ]
